### PR TITLE
Removed "other language" from single.html

### PR DESCRIPTION
**Pull request by NaincyKumariKnoldus**
Hey ! I have removed "other language" url from single.html. Please Review my PR.

### CODE REVIEW

**Comment by apvarun** [comment]
@NaincyKumariKnoldus  Why do you think this needs to be removed?

**Comment by NaincyKumariKnoldus** [comment]
> @NaincyKumariKnoldus Why do you think this needs to be removed?

As your issue was explaining to remove "other language" from single.html. I done that

**Comment by apvarun** [comment]
Ah yes, since the issue #31 was closed already, I didn't notice.

Would you be kind enough to add this change under a config so that its only removed when the config value is set to false. In that way, it would not affect other users

**Comment by apvarun** [comment]
Closing this as I have updated the theme to use the config item `hideOtherLanguages` for the same. This works at page level and site level.

**Pull request closed without merging**
