### PR TITLE
Remove obsolete purgecss

### PR DESCRIPTION
**Pull request by Marty**
Suggested in #43

### CODE REVIEW

**Comment by apvarun** [comment]
Since this is a cleanup PR, lets remove `@fullhuman/postcss-purgecss` package from package.json also and update package-lock

**Comment by Marty** [comment]
@apvarun  Done. Not sure whether I did update the lock file correctly. Made my change and ran `npm i` again. But it deleted a lot of entries. Were all of that transient dependencies?

**Comment by apvarun** [comment]
@Marty The change in package-lock was because of the use of npm v6 instead of npm v7 or v8

**Comment by Marty** [comment]
@apvarun Thanks for the hint, I did this again and this time with `8.5.0` :)

**Pull request merged**
